<?php header("Content-type: text/xml"); ?>
<translation>
   <item name="btn_label_start"><![CDATA[СТАРТ]]></item>
  <item name="btn_label_loading"><![CDATA[ЗАРЕЖДАНЕ]]></item>
  <item name="btn_label_loadstarsystem"><![CDATA[ЗВЕЗДНАТА СИСТЕМА СЕ ЗАРЕЖДА]]></item>
  <item name="hint_title_quests"><![CDATA[МИСИИ]]></item>
  <item name="hint_title_quests_long"><![CDATA[Мисии]]></item>
  <item name="hint_subtitle_quests"><![CDATA[В търсене на приключения?]]></item>
  <item name="hint_description_quests"><![CDATA[Тогава хвърли един поглед на <strong>страницата с мисии</strong>! В главното меню кликни върху <strong>бутона за мисии</strong>, за да приемеш мисията и да се изправиш срещу предизвикателствата.]]></item>
  <item name="hint_title_group"><![CDATA[ГРУПА]]></item>
  <item name="hint_title_group_long"><![CDATA[Група]]></item>
  <item name="hint_subtitle_group"><![CDATA[Не искаш да си сам в битката?]]></item>
  <item name="hint_description_group"><![CDATA[Кликни върху <strong>символа на трите фигури</strong> на <strong>звездната карта</strong>. Покани други играчи в групата си или провери дали нямаш покана.]]></item>
  <item name="hint_title_equipping"><![CDATA[ОБОРУДВАНЕ]]></item>
  <item name="hint_title_equipping_long"><![CDATA[Оборудване]]></item>
  <item name="hint_subtitle_equipping"><![CDATA[Трябват ти нови оръжия?]]></item>
  <item name="hint_description_equipping"><![CDATA[В главното меню в <strong>Хангар</strong> ще намериш оръжия, муниции, бустери, дрони и още много неща!<br><br>Оборудвай кораба си, за да е добре въоръжен за всяка една битка!]]></item>
  <item name="hint_title_configurations"><![CDATA[КОНФИГУРАЦИИ]]></item>
  <item name="hint_title_configurations_long"><![CDATA[Конфигурации]]></item>
  <item name="hint_subtitle_configurations"><![CDATA[Прилагаш различни тактики...?]]></item>
  <item name="hint_description_configurations"><![CDATA[... и не искаш постоянно да преоборудваш кораба си? В такъв случай използвай <strong>2 различни конфигурации</strong> за него.<br><br>В хангара оборудвай и двете конфигурации с елементи. За смяна, натисни <strong>C</strong>!]]></item>
  <item name="hint_title_premium"><![CDATA[ПРЕМИУМ-ПРЕДИМСТВА]]></item>
  <item name="hint_title_premium_long"><![CDATA[Премиум-предимства]]></item>
  <item name="hint_subtitle_premium"><![CDATA[Всички се възползват, а ти?]]></item>
  <item name="hint_description_premium"><![CDATA[Какво чакаш: От <strong>безплатен ремонт на кораби</strong> и много други предимства ще се възползваш с <strong>премиум-пакетите</strong>.]]></item>
  <item name="hint_title_honor"><![CDATA[ЧЕСТ]]></item>
  <item name="hint_title_honor_long"><![CDATA[Чест]]></item>
  <item name="hint_subtitle_honor"><![CDATA[За чест и слава!]]></item>
  <item name="hint_description_honor"><![CDATA[Колкото повече чест печелиш в орбита, толкова по-бързо ще се покачва <strong>рангът ти</strong> в твоята фирма.<br>Изпълнявай мисии и унищожавай възможно най-много врагове и ще спечелиш със сигурност <strong>чест и слава</strong>!]]></item>
  <item name="hint_title_uridium"><![CDATA[УРИДИУМ]]></item>
  <item name="hint_title_uridium_long"><![CDATA[Уридиум]]></item>
  <item name="hint_subtitle_uridium"><![CDATA[Уридиумът е най-ценната руда в орбита!]]></item>
  <item name="hint_description_uridium"><![CDATA[Често извънземните я притежават - унищожи ги! Ще я намериш и в бонус-боксовете.<br> Нямаш късмет в събирането? Тогава я вземи направо от <strong>уридиум</strong> в <strong>главното меню</strong>.]]></item>
  <item name="hint_title_titanic"><![CDATA[Ледени айсберги]]></item>
  <item name="hint_title_titanic_long"><![CDATA[Сто години от потъването на "Титаник"]]></item>
  <item name="hint_subtitle_titanic"><![CDATA[Внимание: Айсберги в DarkOrbit!]]></item>
  <item name="hint_description_titanic"><![CDATA[Преди 100 год. луксозният презокеански кораб "Титаник" се сблъсква с огромен айсберг и потъва. По повод годишнината от този трагичен инцидент <strong>от 14.04. до 17.04.</strong> ще се проведе нашето специално събитие, посветено на "Титаник".]]></item>
  <item name="hint_title_fullscreen"><![CDATA[ЦЯЛ ЕКРАН]]></item>
  <item name="hint_title_fullscreen_long"><![CDATA[Цял екран]]></item>
  <item name="hint_subtitle_fullscreen"><![CDATA[Ново: DarkOrbit на цял екран!]]></item>
  <item name="hint_description_fullscreen"><![CDATA[От сега нататък, можеш да играеш DarkOrbit на <strong>цял екран</strong>.<br>За целта кликни върху съответния бутон в играта!]]></item>
  <item name="hint_title_fullscreenfpupdate"><![CDATA[ЦЯЛ ЕКРАН]]></item>
  <item name="hint_title_fullscreenfpupdate_long"><![CDATA[Цял екран]]></item>
  <item name="hint_subtitle_fullscreenfpupdate"><![CDATA[Желание за още по-впечатляваща DarkOrbit?]]></item>
  <item name="hint_description_fullscreenfpupdate"><![CDATA[<link>Актуализирай своя FlashPlayer</link> и <br>започни да играеш на <strong>цял екран</strong>!]]></item>
  <item name="hint_title_configure_ui"><![CDATA[Конфигуриране на потребителския интерфейс]]></item>
  <item name="hint_title_configure_ui_long"><![CDATA[Конфигуриране на потребителския интерфейс]]></item>
  <item name="hint_subtitle_configure_ui"><![CDATA[Конфигурирай новия потребителски интерфейс в личната си зона.]]></item>
  <item name="hint_description_configure_ui"><![CDATA[<strong>Режимът на конфигурация</strong> се намира в <strong>настройки</strong>, опции за <strong>интерфейса</strong>.]]></item>
</translation>